operations:
  - op_name: "按键-普通攻击-按下"
  - op_name: "按键-移动-左-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-闪避-按下"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-普通攻击-松开"
  - op_name: "按键-闪避-松开"
  - op_name: "按键-移动-左-松开"