# 耀嘉音的上一位和下一位无法识别, 这非常无解

template_name: "速切模板-耀嘉音"
handlers:
  - states: "[前台-耀嘉音]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-耀嘉音]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "耀嘉音-终结技"

      - states: "[耀嘉音-终结技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-耀嘉音-尝试释放终结技"
          - operation_template: "耀嘉音-终结技"
          - op_name: "设置状态"
            state: "自定义-非失衡连携"
            add: 2

      - states: "[自定义-耀嘉音-尝试唱歌, 0, 1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-快速支援换人", "自定义-不使用快速支援", "自定义-无视闪光"]
          - op_name: "等待秒数"
            seconds: 2

      - states: "![按键可用-快速支援, 0, 2]"
        operations:
          - op_name: "设置状态"
            state: "自定义-耀嘉音-尝试唱歌"
          - op_name: "清除状态"
            state_list: ["自定义-快速支援换人", "自定义-不使用快速支援", "自定义-无视闪光"]
          - op_name: "按键-移动-前-按下"
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
            repeat: 3
