template_name: "速切模板-柳"
handlers:
  - states: "[前台-柳]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-柳]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "柳-终结技"

      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "柳-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "柳-闪A"

      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "柳-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.5]"
            operations:
              - op_name: "等待秒数"
                seconds: 0.5
          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[柳-终结技可用] & ![自定义-柳-强化特殊技释放中]"
        operations:
          - operation_template: "柳-终结技"
          - op_name: "设置状态"
            state_list: ["自定义-合轴时间"]

      - states: "[柳-特殊技可用]"
        interrupt_states: "![柳-特殊技可用]"
        operations:
          - op_name: "设置状态"
            state_list: ["自定义-柳-强化特殊技释放中"]
          - operation_template: "柳-强化特殊攻击"

      - states: "[自定义-柳-强化特殊技释放中]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-柳-强化特殊技释放中"]
          - operation_template: "柳-流转攻击-下弦合轴"

      - states: ""
        interrupt_states: "[柳-特殊技可用]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-柳-强化特殊技释放中"]
          - operation_template: "柳-普通攻击合轴"