template_name: "速切模板-薇薇安"
handlers:
  - states: "[前台-薇薇安]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-薇薇安]"
    sub_handlers:
      - states: "[自定义-终结技被强制释放, 0, 1]"
        operations:
          - operation_template: "薇薇安-终结技"

      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "薇薇安-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        operations:
          - operation_template: "薇薇安-闪A"

      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - operation_template: "薇薇安-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.2]|[按键-切换角色-上一个, 0, 0.2])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.2]"
            sub_handlers:
              - states: "[薇薇安-终结技可用]"
                operations:
                  - operation_template: "薇薇安-终结技"
              - states: "[薇薇安-特殊技可用]"
                operations:
                  - operation_template: "薇薇安-快速支援强化特殊技"
              - states: "![薇薇安-特殊技可用]"
                operations:
                  - operation_template: "薇薇安-快速支援"

      - states: "[薇薇安-终结技可用]"
        operations:
          - operation_template: "薇薇安-终结技"

      - states: "[薇薇安-特殊技可用]"
        operations:
          - op_name: "清除状态"
            state: "自定义-不使用快速支援"
          - operation_template: "薇薇安-强化特殊技合轴"

      - states: ""
        debug_name: "走了走了"
        operations:
          - op_name: "设置状态"
            state: "自定义-合轴时间"
          - operation_template: "薇薇安-3A"
          - op_name: "设置状态"
            state: "自定义-合轴时间"
          - operation_template: "薇薇安-4A突刺"
