idx: 1
op_list:
- data:
  - '385'
  - '1092'
  op_type: move
- data:
  - '386'
  - '1123'
  op_type: move
- data:
  - '366'
  - '1137'
  op_type: move
- data:
  - '357'
  - '1070'
  op_type: move
tp_area_id: former_research_center
tp_name: 科研院西侧
